use std::collections::HashMap;

use crate::diagnostic::{Diagnostic, has_errors};
use crate::eval::Value;
use crate::ir::{
    IrBinaryOp, IrExpr, IrFunction, IrProgram, IrSummary, IrUnaryOp, lower_checked_program,
};
use crate::model::Program;
use crate::sampling::{cartesian_product, samples_for_type};

#[derive(Clone, Debug)]
pub struct RustBackendSummary {
    pub diagnostics: Vec<Diagnostic>,
    pub ir_summary: IrSummary,
    pub rust: Option<GeneratedRustProgram>,
}

impl RustBackendSummary {
    pub fn ok(&self) -> bool {
        self.rust.is_some() && !has_errors(&self.diagnostics)
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedRustProgram {
    pub backend: String,
    pub ir_version: String,
    pub source: String,
    pub functions: Vec<GeneratedRustFunction>,
    pub tests: Vec<GeneratedRustTest>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedRustFunction {
    pub symbol: String,
    pub rust_name: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedRustTest {
    pub symbol: String,
    pub kind: String,
    pub example_index: Option<usize>,
    pub property_index: Option<usize>,
    pub sample_index: Option<usize>,
    pub rust_name: String,
}

pub fn generate_checked_rust(
    program: &Program,
    parse_diagnostics: Vec<Diagnostic>,
) -> RustBackendSummary {
    let ir_summary = lower_checked_program(program, parse_diagnostics);
    let mut diagnostics = ir_summary.diagnostics.clone();
    let Some(ir) = &ir_summary.ir else {
        return RustBackendSummary {
            diagnostics,
            ir_summary,
            rust: None,
        };
    };

    match generate_rust_program(ir) {
        Ok(rust) => RustBackendSummary {
            diagnostics,
            ir_summary,
            rust: Some(rust),
        },
        Err(mut backend_diagnostics) => {
            diagnostics.append(&mut backend_diagnostics);
            RustBackendSummary {
                diagnostics,
                ir_summary,
                rust: None,
            }
        }
    }
}

fn generate_rust_program(ir: &IrProgram) -> Result<GeneratedRustProgram, Vec<Diagnostic>> {
    let mut diagnostics = Vec::new();
    let rust_names = rust_function_names(&ir.functions);
    let signatures = rust_function_signatures(&ir.functions);
    let mut rendered_functions = Vec::new();
    let mut rendered_tests = Vec::new();
    let mut generated_functions = Vec::new();
    let mut generated_tests = Vec::new();
    let mut allocated_test_names = HashMap::<String, usize>::new();

    for function in &ir.functions {
        if function.effects != ["pure"] {
            diagnostics.push(
                Diagnostic::error(
                    "RustBackendUnsupportedEffect",
                    format!(
                        "Rust backend currently only emits pure functions; `{}` declares effects {}.",
                        function.symbol,
                        function.effects.join(", ")
                    ),
                    Some(function.symbol.clone()),
                )
                .with_data("symbol", function.symbol.clone())
                .with_data("effects", function.effects.join(", ")),
            );
            continue;
        }

        let Some(rust_name) = rust_names.get(&function.symbol).cloned() else {
            diagnostics.push(Diagnostic::error(
                "RustBackendNameError",
                format!(
                    "No generated Rust name was allocated for `{}`.",
                    function.symbol
                ),
                Some(function.symbol.clone()),
            ));
            continue;
        };

        match render_function(function, &rust_name, &rust_names, &signatures) {
            Ok(source) => {
                rendered_functions.push(source);
                generated_functions.push(GeneratedRustFunction {
                    symbol: function.symbol.clone(),
                    rust_name,
                });
                match render_function_tests(
                    function,
                    &rust_names,
                    &signatures,
                    &mut allocated_test_names,
                ) {
                    Ok((test_sources, test_rows)) => {
                        rendered_tests.extend(test_sources);
                        generated_tests.extend(test_rows);
                    }
                    Err(mut function_diagnostics) => diagnostics.append(&mut function_diagnostics),
                }
            }
            Err(mut function_diagnostics) => diagnostics.append(&mut function_diagnostics),
        }
    }

    if !diagnostics.is_empty() {
        return Err(diagnostics);
    }

    let mut source = String::new();
    source.push_str("// Generated by `serow compile rust` from checked serow.ir.v0.\n");
    source.push_str("// The .serow source remains the source of truth.\n\n");
    source.push_str(&rendered_functions.join("\n\n"));
    source.push('\n');
    if !rendered_tests.is_empty() {
        source.push_str("\n#[cfg(test)]\nmod tests {\n");
        source.push_str("    use super::*;\n\n");
        source.push_str(&rendered_tests.join("\n\n"));
        source.push_str("\n}\n");
    }

    Ok(GeneratedRustProgram {
        backend: "serow.rust.v0".to_string(),
        ir_version: ir.version.clone(),
        source,
        functions: generated_functions,
        tests: generated_tests,
    })
}

fn render_function(
    function: &IrFunction,
    rust_name: &str,
    rust_names: &HashMap<String, String>,
    signatures: &HashMap<String, RustFunctionSignature>,
) -> Result<String, Vec<Diagnostic>> {
    let mut diagnostics = Vec::new();
    let mut variables = HashMap::new();
    let mut variable_types = HashMap::new();
    let mut allocated_params = HashMap::<String, usize>::new();
    let mut params = Vec::new();
    for param in &function.params {
        let rust_type = match rust_type(&param.type_name) {
            Ok(rust_type) => rust_type,
            Err(message) => {
                diagnostics.push(unsupported_type_diagnostic(
                    function,
                    &param.type_name,
                    &message,
                ));
                continue;
            }
        };
        let rust_param_name = allocate_rust_identifier(&param.name, &mut allocated_params);
        variables.insert(param.name.clone(), rust_param_name.clone());
        variable_types.insert(param.name.clone(), param.type_name.clone());
        params.push(format!("{rust_param_name}: {rust_type}"));
    }
    let result_name = allocate_rust_identifier("result", &mut allocated_params);
    let return_type = match rust_type(&function.return_type) {
        Ok(rust_type) => rust_type,
        Err(message) => {
            diagnostics.push(unsupported_type_diagnostic(
                function,
                &function.return_type,
                &message,
            ));
            ""
        }
    };
    if !diagnostics.is_empty() {
        return Err(diagnostics);
    }

    let mut precondition_guards = Vec::new();
    for (index, requirement) in function.requires.iter().enumerate() {
        let requirement = render_expr(
            requirement,
            &variables,
            &variable_types,
            rust_names,
            signatures,
        )
        .map_err(|message| vec![backend_error(function, message)])?;
        if requirement.type_name != "Bool" {
            return Err(vec![backend_error(
                function,
                format!(
                    "Lowered precondition #{} has type {}, expected Bool.",
                    index + 1,
                    requirement.type_name
                ),
            )]);
        }
        precondition_guards.push(format!(
            "    assert!({}, {});",
            strip_outer_parens(&requirement.code),
            rust_string_literal(&format!(
                "Serow precondition failed for {} requires #{}",
                function.symbol,
                index + 1
            ))
        ));
    }

    let body = render_expr(
        &function.body,
        &variables,
        &variable_types,
        rust_names,
        signatures,
    )
    .map(|body| strip_outer_parens(&body.code).to_string())
    .map_err(|message| vec![backend_error(function, message)])?;

    let mut contract_variables = variables;
    let mut contract_variable_types = variable_types;
    contract_variables.insert("result".to_string(), result_name.clone());
    contract_variable_types.insert("result".to_string(), function.return_type.clone());

    let mut postcondition_guards = Vec::new();
    for (index, contract) in function.ensures.iter().enumerate() {
        let contract = render_expr(
            contract,
            &contract_variables,
            &contract_variable_types,
            rust_names,
            signatures,
        )
        .map_err(|message| vec![backend_error(function, message)])?;
        if contract.type_name != "Bool" {
            return Err(vec![backend_error(
                function,
                format!(
                    "Lowered postcondition #{} has type {}, expected Bool.",
                    index + 1,
                    contract.type_name
                ),
            )]);
        }
        postcondition_guards.push(format!(
            "    assert!({}, {});",
            strip_outer_parens(&contract.code),
            rust_string_literal(&format!(
                "Serow postcondition failed for {} ensures #{}",
                function.symbol,
                index + 1
            ))
        ));
    }

    let precondition_block = if precondition_guards.is_empty() {
        String::new()
    } else {
        format!("{}\n", precondition_guards.join("\n"))
    };
    let postcondition_block = if postcondition_guards.is_empty() {
        String::new()
    } else {
        format!("\n{}", postcondition_guards.join("\n"))
    };
    Ok(format!(
        "pub fn {rust_name}({}) -> {return_type} {{\n{precondition_block}    let {result_name} = {body};{postcondition_block}\n    {result_name}\n}}",
        params.join(", ")
    ))
}

fn render_function_tests(
    function: &IrFunction,
    rust_names: &HashMap<String, String>,
    signatures: &HashMap<String, RustFunctionSignature>,
    allocated_test_names: &mut HashMap<String, usize>,
) -> Result<(Vec<String>, Vec<GeneratedRustTest>), Vec<Diagnostic>> {
    let variables = HashMap::new();
    let variable_types = HashMap::new();
    let mut rendered_tests = Vec::new();
    let mut generated_tests = Vec::new();

    for (index, example) in function.examples.iter().enumerate() {
        let rendered = render_expr(example, &variables, &variable_types, rust_names, signatures)
            .map_err(|message| vec![backend_error(function, message)])?;
        if rendered.type_name != "Bool" {
            return Err(vec![backend_error(
                function,
                format!(
                    "Lowered example #{} has type {}, expected Bool.",
                    index + 1,
                    rendered.type_name
                ),
            )]);
        }

        let test_name = allocate_rust_identifier(
            &format!("test_{}_example_{}", function.symbol, index + 1),
            allocated_test_names,
        );
        rendered_tests.push(format!(
            "    #[test]\n    fn {test_name}() {{\n        assert!({}, {});\n    }}",
            strip_outer_parens(&rendered.code),
            rust_string_literal(&format!(
                "Serow example failed for {} example #{}",
                function.symbol,
                index + 1
            ))
        ));
        generated_tests.push(GeneratedRustTest {
            symbol: function.symbol.clone(),
            kind: "example".to_string(),
            example_index: Some(index + 1),
            property_index: None,
            sample_index: None,
            rust_name: test_name,
        });
    }

    for property in &function.properties {
        let mut sample_sets = Vec::new();
        for variable in &property.variables {
            let Some(samples) = samples_for_type(&variable.type_name) else {
                return Err(vec![unsupported_type_diagnostic(
                    function,
                    &variable.type_name,
                    &format!(
                        "No deterministic Rust backend samples exist for property variable `{}`.",
                        variable.name
                    ),
                )]);
            };
            sample_sets.push(samples);
        }
        for (sample_offset, sample_values) in
            cartesian_product(&sample_sets).into_iter().enumerate()
        {
            let sample_index = sample_offset + 1;
            let mut variables = HashMap::new();
            let mut variable_types = HashMap::new();
            let mut allocated_variables = HashMap::<String, usize>::new();
            let mut bindings = Vec::new();
            for (variable, value) in property.variables.iter().zip(sample_values.iter()) {
                let rust_variable =
                    allocate_rust_identifier(&variable.name, &mut allocated_variables);
                variables.insert(variable.name.clone(), rust_variable.clone());
                variable_types.insert(variable.name.clone(), variable.type_name.clone());
                bindings.push(format!(
                    "        let {rust_variable} = {};",
                    render_sample_value(value)
                ));
            }
            let rendered = render_expr(
                &property.expression,
                &variables,
                &variable_types,
                rust_names,
                signatures,
            )
            .map_err(|message| vec![backend_error(function, message)])?;
            if rendered.type_name != "Bool" {
                return Err(vec![backend_error(
                    function,
                    format!(
                        "Lowered property #{} sample #{} has type {}, expected Bool.",
                        property.index, sample_index, rendered.type_name
                    ),
                )]);
            }

            let test_name = allocate_rust_identifier(
                &format!(
                    "test_{}_property_{}_sample_{}",
                    function.symbol, property.index, sample_index
                ),
                allocated_test_names,
            );
            let binding_block = if bindings.is_empty() {
                String::new()
            } else {
                format!("{}\n", bindings.join("\n"))
            };
            rendered_tests.push(format!(
                "    #[test]\n    fn {test_name}() {{\n{binding_block}        assert!({}, {});\n    }}",
                strip_outer_parens(&rendered.code),
                rust_string_literal(&format!(
                    "Serow property failed for {} property #{} sample #{}",
                    function.symbol, property.index, sample_index
                ))
            ));
            generated_tests.push(GeneratedRustTest {
                symbol: function.symbol.clone(),
                kind: "property".to_string(),
                example_index: None,
                property_index: Some(property.index),
                sample_index: Some(sample_index),
                rust_name: test_name,
            });
        }
    }

    Ok((rendered_tests, generated_tests))
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct RustFunctionSignature {
    params: Vec<String>,
    return_type: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct RenderedExpr {
    code: String,
    type_name: String,
}

fn render_expr(
    expr: &IrExpr,
    variables: &HashMap<String, String>,
    variable_types: &HashMap<String, String>,
    rust_names: &HashMap<String, String>,
    signatures: &HashMap<String, RustFunctionSignature>,
) -> Result<RenderedExpr, String> {
    match expr {
        IrExpr::Int(value) => Ok(rendered(value.to_string(), "Int")),
        IrExpr::Bool(value) => Ok(rendered(value.to_string(), "Bool")),
        IrExpr::Text(value) => Ok(rendered(
            format!("String::from({})", rust_string_literal(value)),
            "Text",
        )),
        IrExpr::Var(name) => {
            let variable = variables
                .get(name)
                .ok_or_else(|| format!("Unknown lowered variable `{name}`."))?;
            let type_name = variable_types
                .get(name)
                .ok_or_else(|| format!("Unknown lowered variable type for `{name}`."))?;
            let code = if type_name == "Text" {
                format!("{variable}.clone()")
            } else {
                variable.clone()
            };
            Ok(RenderedExpr {
                code,
                type_name: type_name.clone(),
            })
        }
        IrExpr::Call { target, args, .. } => {
            let rust_name = rust_names
                .get(target)
                .ok_or_else(|| format!("No Rust target was generated for call to `{target}`."))?;
            let signature = signatures
                .get(target)
                .ok_or_else(|| format!("No Rust signature was recorded for call to `{target}`."))?;
            let args = args
                .iter()
                .map(|arg| render_expr(arg, variables, variable_types, rust_names, signatures))
                .collect::<Result<Vec<_>, _>>()?;
            if args.len() != signature.params.len() {
                return Err(format!(
                    "Call to `{target}` has {} lowered arguments, expected {}.",
                    args.len(),
                    signature.params.len()
                ));
            }
            for (index, (arg, expected)) in args.iter().zip(&signature.params).enumerate() {
                if &arg.type_name != expected {
                    return Err(format!(
                        "Call to `{target}` argument {} lowered as {}, expected {}.",
                        index + 1,
                        arg.type_name,
                        expected
                    ));
                }
            }
            Ok(RenderedExpr {
                code: format!(
                    "{rust_name}({})",
                    args.iter()
                        .map(|arg| strip_outer_parens(&arg.code).to_string())
                        .collect::<Vec<_>>()
                        .join(", ")
                ),
                type_name: signature.return_type.clone(),
            })
        }
        IrExpr::Unary { op, expr } => {
            let expr = render_expr(expr, variables, variable_types, rust_names, signatures)?;
            let operator = match op {
                IrUnaryOp::Neg => "-",
                IrUnaryOp::Not => "!",
            };
            let type_name = match op {
                IrUnaryOp::Neg => "Int",
                IrUnaryOp::Not => "Bool",
            };
            Ok(rendered(format!("({operator}{})", expr.code), type_name))
        }
        IrExpr::Binary { op, left, right } => {
            let left = render_expr(left, variables, variable_types, rust_names, signatures)?;
            let right = render_expr(right, variables, variable_types, rust_names, signatures)?;
            let operator = match op {
                IrBinaryOp::Add => "+",
                IrBinaryOp::Sub => "-",
                IrBinaryOp::Mul => "*",
                IrBinaryOp::DivTrunc => "/",
                IrBinaryOp::Rem => "%",
                IrBinaryOp::Eq => "==",
                IrBinaryOp::NotEq => "!=",
                IrBinaryOp::Lt => "<",
                IrBinaryOp::LtEq => "<=",
                IrBinaryOp::Gt => ">",
                IrBinaryOp::GtEq => ">=",
                IrBinaryOp::And => "&&",
                IrBinaryOp::Or => "||",
            };
            let type_name = match op {
                IrBinaryOp::Add if left.type_name == "Text" && right.type_name == "Text" => {
                    return Ok(rendered(
                        format!("format!(\"{{}}{{}}\", {}, {})", left.code, right.code),
                        "Text",
                    ));
                }
                IrBinaryOp::Add => "Int",
                IrBinaryOp::Sub | IrBinaryOp::Mul | IrBinaryOp::DivTrunc | IrBinaryOp::Rem => "Int",
                IrBinaryOp::Eq
                | IrBinaryOp::NotEq
                | IrBinaryOp::Lt
                | IrBinaryOp::LtEq
                | IrBinaryOp::Gt
                | IrBinaryOp::GtEq
                | IrBinaryOp::And
                | IrBinaryOp::Or => "Bool",
            };
            Ok(rendered(
                format!("({} {operator} {})", left.code, right.code),
                type_name,
            ))
        }
        IrExpr::If {
            condition,
            then_expr,
            else_expr,
        } => {
            let condition =
                render_expr(condition, variables, variable_types, rust_names, signatures)?;
            let then_expr =
                render_expr(then_expr, variables, variable_types, rust_names, signatures)?;
            let else_expr =
                render_expr(else_expr, variables, variable_types, rust_names, signatures)?;
            if then_expr.type_name != else_expr.type_name {
                return Err(format!(
                    "Lowered if branches have mismatched types {} and {}.",
                    then_expr.type_name, else_expr.type_name
                ));
            }
            Ok(RenderedExpr {
                code: format!(
                    "if {} {{ {} }} else {{ {} }}",
                    strip_outer_parens(&condition.code),
                    strip_outer_parens(&then_expr.code),
                    strip_outer_parens(&else_expr.code)
                ),
                type_name: then_expr.type_name,
            })
        }
    }
}

fn rendered(code: String, type_name: &str) -> RenderedExpr {
    RenderedExpr {
        code,
        type_name: type_name.to_string(),
    }
}

fn strip_outer_parens(expression: &str) -> &str {
    let Some(inner) = expression
        .strip_prefix('(')
        .and_then(|value| value.strip_suffix(')'))
    else {
        return expression;
    };
    inner
}

fn rust_function_names(functions: &[IrFunction]) -> HashMap<String, String> {
    let mut names = HashMap::new();
    let mut allocated = HashMap::<String, usize>::new();
    for function in functions {
        let rust_name = allocate_rust_identifier(&function.symbol, &mut allocated);
        names.insert(function.symbol.clone(), rust_name);
    }
    names
}

fn rust_function_signatures(functions: &[IrFunction]) -> HashMap<String, RustFunctionSignature> {
    functions
        .iter()
        .map(|function| {
            (
                function.symbol.clone(),
                RustFunctionSignature {
                    params: function
                        .params
                        .iter()
                        .map(|param| param.type_name.clone())
                        .collect(),
                    return_type: function.return_type.clone(),
                },
            )
        })
        .collect()
}

fn rust_type(type_name: &str) -> Result<&'static str, String> {
    match type_name {
        "Int" => Ok("i64"),
        "Bool" => Ok("bool"),
        "Text" => Ok("String"),
        other => Err(format!("Unknown backend type `{other}`.")),
    }
}

fn rust_string_literal(value: &str) -> String {
    let mut escaped = String::from("\"");
    for char in value.chars() {
        match char {
            '"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            char if char.is_control() => escaped.push_str(&format!("\\u{{{:x}}}", char as u32)),
            char => escaped.push(char),
        }
    }
    escaped.push('"');
    escaped
}

fn render_sample_value(value: &Value) -> String {
    match value {
        Value::Int(value) => value.to_string(),
        Value::Bool(value) => value.to_string(),
        Value::Text(value) => format!("String::from({})", rust_string_literal(value)),
    }
}

fn rust_identifier(name: &str) -> String {
    let mut ident = String::from("serow_");
    for char in name.trim_start_matches('@').chars() {
        if char.is_ascii_alphanumeric() || char == '_' {
            ident.push(char);
        } else {
            ident.push('_');
        }
    }
    while ident.contains("__") {
        ident = ident.replace("__", "_");
    }
    if ident.ends_with('_') {
        ident.pop();
    }
    ident
}

fn allocate_rust_identifier(name: &str, allocated: &mut HashMap<String, usize>) -> String {
    let base = rust_identifier(name);
    let count = allocated.entry(base.clone()).or_insert(0);
    *count += 1;
    if *count == 1 {
        base
    } else {
        format!("{base}_{count}")
    }
}

fn unsupported_type_diagnostic(
    function: &IrFunction,
    type_name: &str,
    message: &str,
) -> Diagnostic {
    Diagnostic::error(
        "RustBackendUnsupportedType",
        format!(
            "Rust backend cannot emit `{}` because type `{type_name}` is unsupported: {message}",
            function.symbol
        ),
        Some(function.symbol.clone()),
    )
    .with_data("symbol", function.symbol.clone())
    .with_data("type", type_name.to_string())
}

fn backend_error(function: &IrFunction, message: String) -> Diagnostic {
    Diagnostic::error(
        "RustBackendLoweringError",
        format!(
            "Could not emit Rust for `{}` from lowered IR: {message}",
            function.symbol
        ),
        Some(function.symbol.clone()),
    )
    .with_data("symbol", function.symbol.clone())
}
