use std::collections::HashMap;

use crate::diagnostic::{Diagnostic, has_errors};
use crate::ir::{
    IrBinaryOp, IrExpr, IrFunction, IrProgram, IrSummary, IrUnaryOp, lower_checked_program,
};
use crate::model::Program;

#[derive(Clone, Debug)]
pub struct RustBackendSummary {
    pub diagnostics: Vec<Diagnostic>,
    pub ir_summary: IrSummary,
    pub rust: Option<GeneratedRustProgram>,
}

impl RustBackendSummary {
    pub fn ok(&self) -> bool {
        self.rust.is_some() && !has_errors(&self.diagnostics)
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedRustProgram {
    pub backend: String,
    pub ir_version: String,
    pub source: String,
    pub functions: Vec<GeneratedRustFunction>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedRustFunction {
    pub symbol: String,
    pub rust_name: String,
}

pub fn generate_checked_rust(
    program: &Program,
    parse_diagnostics: Vec<Diagnostic>,
) -> RustBackendSummary {
    let ir_summary = lower_checked_program(program, parse_diagnostics);
    let mut diagnostics = ir_summary.diagnostics.clone();
    let Some(ir) = &ir_summary.ir else {
        return RustBackendSummary {
            diagnostics,
            ir_summary,
            rust: None,
        };
    };

    match generate_rust_program(ir) {
        Ok(rust) => RustBackendSummary {
            diagnostics,
            ir_summary,
            rust: Some(rust),
        },
        Err(mut backend_diagnostics) => {
            diagnostics.append(&mut backend_diagnostics);
            RustBackendSummary {
                diagnostics,
                ir_summary,
                rust: None,
            }
        }
    }
}

fn generate_rust_program(ir: &IrProgram) -> Result<GeneratedRustProgram, Vec<Diagnostic>> {
    let mut diagnostics = Vec::new();
    let rust_names = rust_function_names(&ir.functions);
    let mut rendered_functions = Vec::new();
    let mut generated_functions = Vec::new();

    for function in &ir.functions {
        if function.effects != ["pure"] {
            diagnostics.push(
                Diagnostic::error(
                    "RustBackendUnsupportedEffect",
                    format!(
                        "Rust backend currently only emits pure functions; `{}` declares effects {}.",
                        function.symbol,
                        function.effects.join(", ")
                    ),
                    Some(function.symbol.clone()),
                )
                .with_data("symbol", function.symbol.clone())
                .with_data("effects", function.effects.join(", ")),
            );
            continue;
        }

        let Some(rust_name) = rust_names.get(&function.symbol).cloned() else {
            diagnostics.push(Diagnostic::error(
                "RustBackendNameError",
                format!(
                    "No generated Rust name was allocated for `{}`.",
                    function.symbol
                ),
                Some(function.symbol.clone()),
            ));
            continue;
        };

        match render_function(function, &rust_name, &rust_names) {
            Ok(source) => {
                rendered_functions.push(source);
                generated_functions.push(GeneratedRustFunction {
                    symbol: function.symbol.clone(),
                    rust_name,
                });
            }
            Err(mut function_diagnostics) => diagnostics.append(&mut function_diagnostics),
        }
    }

    if !diagnostics.is_empty() {
        return Err(diagnostics);
    }

    let mut source = String::new();
    source.push_str("// Generated by `serow compile rust` from checked serow.ir.v0.\n");
    source.push_str("// The .serow source remains the source of truth.\n\n");
    source.push_str(&rendered_functions.join("\n\n"));
    source.push('\n');

    Ok(GeneratedRustProgram {
        backend: "serow.rust.v0".to_string(),
        ir_version: ir.version.clone(),
        source,
        functions: generated_functions,
    })
}

fn render_function(
    function: &IrFunction,
    rust_name: &str,
    rust_names: &HashMap<String, String>,
) -> Result<String, Vec<Diagnostic>> {
    let mut diagnostics = Vec::new();
    let mut variables = HashMap::new();
    let mut allocated_params = HashMap::<String, usize>::new();
    let mut params = Vec::new();
    for param in &function.params {
        let rust_type = match rust_type(&param.type_name) {
            Ok(rust_type) => rust_type,
            Err(message) => {
                diagnostics.push(unsupported_type_diagnostic(
                    function,
                    &param.type_name,
                    &message,
                ));
                continue;
            }
        };
        let rust_param_name = allocate_rust_identifier(&param.name, &mut allocated_params);
        variables.insert(param.name.clone(), rust_param_name.clone());
        params.push(format!("{rust_param_name}: {rust_type}"));
    }
    let return_type = match rust_type(&function.return_type) {
        Ok(rust_type) => rust_type,
        Err(message) => {
            diagnostics.push(unsupported_type_diagnostic(
                function,
                &function.return_type,
                &message,
            ));
            ""
        }
    };
    if !diagnostics.is_empty() {
        return Err(diagnostics);
    }

    let body = render_expr(&function.body, &variables, rust_names)
        .map(|body| strip_outer_parens(&body).to_string())
        .map_err(|message| vec![backend_error(function, message)])?;
    Ok(format!(
        "pub fn {rust_name}({}) -> {return_type} {{\n    {body}\n}}",
        params.join(", ")
    ))
}

fn render_expr(
    expr: &IrExpr,
    variables: &HashMap<String, String>,
    rust_names: &HashMap<String, String>,
) -> Result<String, String> {
    match expr {
        IrExpr::Int(value) => Ok(value.to_string()),
        IrExpr::Bool(value) => Ok(value.to_string()),
        IrExpr::Text(_) => {
            Err("Text expressions are not supported by the Rust backend yet.".to_string())
        }
        IrExpr::Var(name) => variables
            .get(name)
            .cloned()
            .ok_or_else(|| format!("Unknown lowered variable `{name}`.")),
        IrExpr::Call { target, args, .. } => {
            let rust_name = rust_names
                .get(target)
                .ok_or_else(|| format!("No Rust target was generated for call to `{target}`."))?;
            let args = args
                .iter()
                .map(|arg| render_expr(arg, variables, rust_names))
                .collect::<Result<Vec<_>, _>>()?;
            Ok(format!("{rust_name}({})", args.join(", ")))
        }
        IrExpr::Unary { op, expr } => {
            let expr = render_expr(expr, variables, rust_names)?;
            let operator = match op {
                IrUnaryOp::Neg => "-",
                IrUnaryOp::Not => "!",
            };
            Ok(format!("({operator}{expr})"))
        }
        IrExpr::Binary { op, left, right } => {
            let left = render_expr(left, variables, rust_names)?;
            let right = render_expr(right, variables, rust_names)?;
            let operator = match op {
                IrBinaryOp::Add => "+",
                IrBinaryOp::Sub => "-",
                IrBinaryOp::Mul => "*",
                IrBinaryOp::DivTrunc => "/",
                IrBinaryOp::Rem => "%",
                IrBinaryOp::Eq => "==",
                IrBinaryOp::NotEq => "!=",
                IrBinaryOp::Lt => "<",
                IrBinaryOp::LtEq => "<=",
                IrBinaryOp::Gt => ">",
                IrBinaryOp::GtEq => ">=",
                IrBinaryOp::And => "&&",
                IrBinaryOp::Or => "||",
            };
            Ok(format!("({left} {operator} {right})"))
        }
        IrExpr::If {
            condition,
            then_expr,
            else_expr,
        } => {
            let condition = render_expr(condition, variables, rust_names)?;
            let then_expr = render_expr(then_expr, variables, rust_names)?;
            let else_expr = render_expr(else_expr, variables, rust_names)?;
            Ok(format!(
                "if {} {{ {} }} else {{ {} }}",
                strip_outer_parens(&condition),
                strip_outer_parens(&then_expr),
                strip_outer_parens(&else_expr)
            ))
        }
    }
}

fn strip_outer_parens(expression: &str) -> &str {
    let Some(inner) = expression
        .strip_prefix('(')
        .and_then(|value| value.strip_suffix(')'))
    else {
        return expression;
    };
    inner
}

fn rust_function_names(functions: &[IrFunction]) -> HashMap<String, String> {
    let mut names = HashMap::new();
    let mut allocated = HashMap::<String, usize>::new();
    for function in functions {
        let rust_name = allocate_rust_identifier(&function.symbol, &mut allocated);
        names.insert(function.symbol.clone(), rust_name);
    }
    names
}

fn rust_type(type_name: &str) -> Result<&'static str, String> {
    match type_name {
        "Int" => Ok("i64"),
        "Bool" => Ok("bool"),
        "Text" => {
            Err("Text lowering needs an ownership policy and is not emitted yet.".to_string())
        }
        other => Err(format!("Unknown backend type `{other}`.")),
    }
}

fn rust_identifier(name: &str) -> String {
    let mut ident = String::from("serow_");
    for char in name.trim_start_matches('@').chars() {
        if char.is_ascii_alphanumeric() || char == '_' {
            ident.push(char);
        } else {
            ident.push('_');
        }
    }
    while ident.contains("__") {
        ident = ident.replace("__", "_");
    }
    if ident.ends_with('_') {
        ident.pop();
    }
    ident
}

fn allocate_rust_identifier(name: &str, allocated: &mut HashMap<String, usize>) -> String {
    let base = rust_identifier(name);
    let count = allocated.entry(base.clone()).or_insert(0);
    *count += 1;
    if *count == 1 {
        base
    } else {
        format!("{base}_{count}")
    }
}

fn unsupported_type_diagnostic(
    function: &IrFunction,
    type_name: &str,
    message: &str,
) -> Diagnostic {
    Diagnostic::error(
        "RustBackendUnsupportedType",
        format!(
            "Rust backend cannot emit `{}` because type `{type_name}` is unsupported: {message}",
            function.symbol
        ),
        Some(function.symbol.clone()),
    )
    .with_data("symbol", function.symbol.clone())
    .with_data("type", type_name.to_string())
}

fn backend_error(function: &IrFunction, message: String) -> Diagnostic {
    Diagnostic::error(
        "RustBackendLoweringError",
        format!(
            "Could not emit Rust for `{}` from lowered IR: {message}",
            function.symbol
        ),
        Some(function.symbol.clone()),
    )
    .with_data("symbol", function.symbol.clone())
}
